language: objective-c
osx_image: xcode12.2
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
install:
  - bundle install
script:
  - bundle exec fastlane build_framework source_code_url:https://$GITHUB_TOKEN@$SOURCE_CODE_URL
notifications:
   webhooks: $DITALK_WEBHOOK_TOKEN